sudo: false

language: node_js
node_js:
  - 10.13.0

before_install:
  - yarn add global nwb 
  - yarn add codecov.io coveralls


install:
  - yarn install

script:
  - yarn test

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - master
    - development
